"""
Macro Agent report builder — shared by run_macro_agent.py and run_weekly_fetch.py.

Generates macro_agent_data_W{week}.md for evidence/Week X/ in the group repo.
Macro Lead fills in Fed rates, calendar, earnings, news, and bias after the script runs.
"""

from datetime import datetime

MACRO_COMMODITIES = {"CL": "WTI Crude Oil", "GC": "Gold", "DX": "DXY (Dollar)"}


def build_finviz_markdown(rows: list[dict]) -> str:
    lines = [
        "## Finviz Futures Performance (1W)",
        "",
        "| Ticker | Name | Group | Weekly % |",
        "|--------|------|-------|----------|",
    ]
    for row in sorted(rows, key=lambda r: r["perf_pct"], reverse=True):
        lines.append(
            f"| {row['ticker']} | {row['label']} | {row['group']} | {row['perf_pct']:+.2f}% |"
        )
    lines.append("")
    lines.append(
        f"*Fetched: {rows[0]['fetched_at'] if rows else 'N/A'} from finviz.com/futures_performance*"
    )
    return "\n".join(lines)


def build_commodities_section(rows: list[dict]) -> str:
    lines = ["## Commodities & Dollar (Finviz Futures 1W)", ""]
    by_ticker = {r["ticker"]: r for r in rows}
    for ticker, name in MACRO_COMMODITIES.items():
        row = by_ticker.get(ticker)
        if row:
            direction = (
                "Rising" if row["perf_pct"] > 0 else "Falling" if row["perf_pct"] < 0 else "Flat"
            )
            lines.append(
                f"- **{name}**: weekly change {row['perf_pct']:+.2f}%, direction: {direction}"
            )
        else:
            lines.append(f"- **{name}**: not found in this week's fetch")
    lines.append("")
    lines.append(
        "> Macro Lead: add cross-asset implication, Fed rates, calendar, earnings, news, and bias below."
    )
    return "\n".join(lines)


def build_sectors_markdown(sectors: list[dict]) -> str:
    lines = [
        "## Yahoo Finance Sectors (5D via yfinance)",
        "",
        "| ETF | Sector | Price | Day Return % |",
        "|-----|--------|-------|--------------|",
    ]
    for row in sorted(sectors, key=lambda s: s["day_return_pct"], reverse=True):
        sign = "+" if row["day_return_pct"] >= 0 else ""
        lines.append(
            f"| {row['symbol']} | {row['name']} | {row['price']} | {sign}{row['day_return_pct']}% |"
        )
    lines.append("")
    lines.append(f"*Fetched: {sectors[0]['fetched_at'] if sectors else 'N/A'} via yfinance*")
    return "\n".join(lines)


def build_macro_report(
    week: int,
    finviz_rows: list[dict],
    sectors: list[dict],
    source: str = "macro_agent_script",
) -> str:
    stamp = datetime.now().strftime("%d %b %Y")
    commodities = build_commodities_section(finviz_rows)

    return f"""# MACRO AGENT DATA FETCH — WEEK {week} — SOURCE: R4 ({source})

*Auto-generated by TradeKyaMal Macro Agent script on {stamp}. Macro Lead must complete Fed, calendar, earnings, news, bias.*

{commodities}

## Fed & Rates (CME FedWatch + Treasury.gov)
- Current Fed rate: [fill in]
- Next FOMC date: [fill in]. Hold/Hike/Cut probabilities: [fill in]
- 2Y / 10Y / 30Y yields: [fill in]
- Implication: [fill in]

## Week-Ahead Calendar (TradingEconomics)
- [Add events — or attach screenshot from tradingeconomics.com/calendar]

## Key Earnings (Earnings Whispers)
- [Add earnings]

## Confirmed News (Reuters / AP)
- [Add news]

## MACRO BIAS: [Neutral-Bullish / Neutral / Cautious]
## PRIMARY DRIVER: [fill in]
## CONFIDENCE: [Low / Medium / High]
## INVALIDATION: [fill in]

---

{build_finviz_markdown(finviz_rows)}

---

{build_sectors_markdown(sectors)}

Sources accessed: {stamp}. Finviz + yfinance fetched by Macro Agent script. Remaining sections from approved tools.
"""
